### ISSUE TITLE
client only?

### ISSUE THREAD

**Issue by dcsan** [miktam/loggly#1]
when you say a "client implementation" do you mean this works only from client side in meteor?
or that it is a "loggly client" that will work both client and server side?

**Comment by Art1Sec8** [comment]
@dcsan The current package only works on the server.  But I've put together a pull request that will add logger functionality to the client side.  You just need to make sure to create the Logger object on the server side (in order to set up the Loggly settings).  Then you should be able to log from both the client and server.

**Comment by miktam** [comment]
Merged https://github.com/avrora/loggly/pull/2
